### PR TITLE
feat(rpc): implement `ledger_getEvents`

### LINKED ISSUE #1037: Add `ledger_getEvents` to `sov_ledger_rpc::RpcClient`
PR https://github.com/Sovereign-Labs/sovereign-sdk/pull/1032 introduced a `jsonrpsee` client for the ledger RPC API, but it's missing `ledger_getEvents`. Unfortunately, `jsonrpsee`'s `rpc` macro is not flexible enough to allow for the kind of parameter serialization logic that we need for this method. All we need is a `Vec<EventIdentifier>` e.g. `"params": [1, 2, 42]`, but `jsonrpsee` serializes the `event_ids` as `"params": [[1, 2, 42]]`.

The solution seems to be replacing the `rpc` macro -generated trait `RpcClient` and replacing it with a hand-written one, which correctly serializes all parameter types.

### PR DESCRIPTION
**Pull request by rkrasiuk**
# Description

Implement `ledger_getEvents` through the extension trait. Not a fan of this solution but it saves you from the pain of having to handroll your own rpc macro.

## Linked Issues
- Fixes #1037

## Testing
Added `ledger_getEvents` to `getters_succeed` test

### CODE REVIEW

**Review by neysofu — COMMENTED** [review]
Hi @rkrasiuk, thanks for the PR! Greatly appreciated.

The solution looks good. The extra trait approach is quite painful, although less than rolling our own hand-written client trait.

Sooner or later, I'd still like us to roll our own trait because it allows up to completely abstract away other serialization details (e.g. `HexHash`, there's no good reason for that to be part of the public crate API). In the meantime, maybe there we can avoid having the extra trait by extending the server implementation to accept both parameter types: the correct one, and `jsonrpsee`'s auto-generated one. I have tried writing an MVP here: https://github.com/Sovereign-Labs/sovereign-sdk/compare/nightly...filippo/get-events-rpc.

What do you think? I'm unsure myself what I prefer.

**Comment by rkrasiuk** [comment]
hey @neysofu, i'm a bit at the crossroads as well. my preference would be for rpc to have strict behavior, but i like the code for your solution more, so i'll leave it up to you to decide :) 

on the sidenote, could you point me to some good first issues i could take? very few seem to be tagged

**Comment by neysofu** [comment]
It's great that you want to pick up more issues, @rkrasiuk, thank you! I'll chat with the team later today and we'll tag a few issues as `good-first-issue` or something of that sort to help newcomers, and I can ping you when we do so.

As for the `ledger_getEvents` pattern, I think the nested parameter hack is good enough for now – when we hand-roll our own client trait, we can then remove the pathological case handler on the server's side, and the test for it.

Let me know if you're able to rewrite the branch history to include the changes in https://github.com/Sovereign-Labs/sovereign-sdk/commit/d86f02d8dbe5d17da25b6d84e92eeef9b332218d. Feel free to modify the test, comments, or anything that you'd like to improve on. In the meantime, I'll create a new issue to track the hand-written client trait development.

**Comment by rkrasiuk** [comment]
no need to cherry-pick then, that solution looks good enough. closing in favor of https://github.com/Sovereign-Labs/sovereign-sdk/commit/d86f02d8dbe5d17da25b6d84e92eeef9b332218d

**Comment by neysofu** [comment]
Hey @rkrasiuk!

I think there's few issues you could take on:
- https://github.com/Sovereign-Labs/sovereign-sdk/issues/1066 which is actually what we discussed here, i.e. hand-writing our own client trait with proper serialization and hiding details from the API such as `HexString`.
- https://github.com/Sovereign-Labs/sovereign-sdk/issues/544
- There's no issue for this one (yet), but basically all of our modules (as in, Sovereign SDK modules, not Rust modules) have some misplaced unit tests in `module/src/tests.rs` which should actually be integration tests in `module/tests/`. We'd like to change this everywhere within the workspace, and expose private items if necessary.

**Comment by citizen-stig** [comment]
Additional issue that can be good to fix for sequencer:

* https://github.com/Sovereign-Labs/sovereign-sdk/issues/1090

**Pull request closed without merging**
