### PR TITLE
[TEST]: Verify license checking works

### PR DESCRIPTION
**Pull request by neysofu**
I'm adding a dependency to [`nettle`](https://gitlab.com/sequoia-pgp/nettle-rs), which is GPL-versioned, just to see if `dependency-review` will trigger an error. Also testing with https://github.com/rnd-ash/ecu_diagnostics. **This PR will not be merged.**

### CODE REVIEW

**Comment by neysofu** [comment]
Conclusion: https://github.com/actions/dependency-review-action seems to be very poor at detecting dependencies' licenses and doesn't raise any issues when adding a GPL-licensed crate to the workspace. We should evaluate switching to [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny), which is much more stringent.

cc @bkolad @citizen-stig

**Comment by citizen-stig** [comment]
@neysofu `cargo-udeps` looks like a good choice, I had pretty good experience with it.

**Comment by neysofu** [comment]
`cargo-udeps` is great – it can't do license auditing though, or can it?

**Comment by citizen-stig** [comment]
Sorry, I meant `cargo-deny` =)

**Comment by neysofu** [comment]
Gotcha! Agreed, `cargo-deny` is best for this. Let's switch.

**Pull request closed without merging**
